baseurl = "https://joaoarthurbm.github.io/arquitetura-de-software"
title = "Arquitetura de Software"
copyright = "Copyright &copy; 2020 - João Arthur Brunet"
canonifyurls = true
theme = "kiera"
themesDir = "themes"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "João Arthur Brunet"
    github = "http://joaoarthurbm.github.io"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "joaobrunet"
    instagram = "joaoarthurbm"

[params]
    tagline = "João Arthur Brunet <br> Computação @ UFCG"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
